### ISSUE TITLE
Visual Counter of Completion during the import (export) process 

### ISSUE THREAD

**Issue by yhegazy** [fullstackedorg/editor#68]
Hello, i hope you're doing well. i found you on reddit. this is a great application so far, but i have a few concerns that hopefully you can address.  Currently on an Intel MacOS. 

### What was the problem?

When Importing into Fullstacked, the import button goes gray and the application seems to be in a "frozen state".  Only quitting and relaunching the app shows the imported directory (but no files).

### Solution
Consider implementing a progress bar or visual indicator to display task completion status, along with a continue/launch button that becomes available once the task is complete.

**Comment by cplepage** [comment]
@yhegazy yeah this happens with too large project (too heavy .zip).
Your solution makes a lot of sense. If you ever want to try to make it, PRs are more than welcome.

I added your issue to the backlog, will consider it when refactoring the [project-view](editor/views/project-new/index.ts)
